# We need to use two separate build hosts for each architecture because of how
# slow everything is here. Unfortunately, that means we lose the tooling which
# allows us to push everything as one single manifest.
#
# For now, we're forced to push per-architecture images and then create a
# manifest from them. This can be replaced once the Docker CLI supports pushing
# images by reference instead of by tag, though it could also be done by
# creating new tooling which interacts with the Docker registry API directly.

name: Container
on:
  push:
    tags:
      - 'v*'
permissions:
  packages: write
env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository_owner }}/viceroy
jobs:
  build_amd64:
    name: Build AMD64 Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build container
        run: |
          docker build \
            -t ${{ env.DOCKER_IMAGE }}:latest-amd64 \
            .
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin ghcr.io
      - name: Push container
        run: |
          docker tag ${{ env.DOCKER_IMAGE }}:latest-amd64 ${{ env.DOCKER_IMAGE }}:${{ github.ref_name }}-amd64
          docker push ${{ env.DOCKER_IMAGE }}:latest-amd64
          docker push ${{ env.DOCKER_IMAGE }}:${{ github.ref_name }}-amd64

  build_arm64:
    name: Build ARM64 Container
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build container
        run: |
          docker build \
            -t ${{ env.DOCKER_IMAGE }}:latest-arm64 \
            .
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin ghcr.io
      - name: Push container
        run: |
          docker tag ${{ env.DOCKER_IMAGE }}:latest-arm64 ${{ env.DOCKER_IMAGE }}:${{ github.ref_name }}-arm64
          docker push ${{ env.DOCKER_IMAGE }}:latest-arm64
          docker push ${{ env.DOCKER_IMAGE }}:${{ github.ref_name }}-arm64

  bundle-manifests:
    name: Bundle manifests
    needs: [build_amd64, build_arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin ghcr.io
      - name: Create manifests
        run: |
          docker buildx imagetools create \
            -t ${{ env.DOCKER_IMAGE }}:${{ github.ref_name }} -t ${{ env.DOCKER_IMAGE }}:latest \
            ${{ env.DOCKER_IMAGE }}:${{ github.ref_name }}-amd64 \
            ${{ env.DOCKER_IMAGE }}:${{ github.ref_name }}-arm64
